/**
 *
 * @type {{ALPHANUMERIC: string, ARGUMENT: string, ARRAY: string, BOOLEAN: string, BUFFER: string, DATE: string, ERROR: string, FLOAT: string, FLOAT32ARRAY: string, FLOAT64ARRAY: string, FUNCTION: string, GENERATORFUNCTION: string, INT: string, INT16ARRAY: string, INT32ARRAY: string, INT8ARRAY: string, MAP: string, NULL: string, NUMBER: string, OBJECT: string, PROMISE: string, REGEXP: string, SET: string, STRING: string, SYMBOL: string, UINT16ARRAY: string, UINT32ARRAY: string, UINT8ARRAY: string, UINT8CLAMPEDARRAY: string, UNDEFINED: string, WEAKMAP: string, WEAKSET: string}}
 */
module.exports = {
    ARGUMENTS: 'arguments',
    ARRAY: 'array',
    BOOLEAN: 'boolean',
    BUFFER: 'buffer',
    DATE: 'date',
    ERROR: 'error',
    FLOAT32ARRAY: 'float32array',
    FLOAT64ARRAY: 'float64array',
    FUNCTION: 'function',
    GENERATORFUNCTION: 'generatorfunction',
    INT16ARRAY: 'int16array',
    INT32ARRAY: 'int32array',
    INT8ARRAY: 'int8array',
    MAP: 'map',
    NULL: 'null',
    NUMBER: 'number',
    OBJECT: 'object',
    PROMISE: 'promise',
    REGEXP: 'regexp',
    SET: 'set',
    STRING: 'string',
    SYMBOL: 'symbol',
    UINT16ARRAY: 'uint16array',
    UINT32ARRAY: 'uint32array',
    UINT8ARRAY: 'uint8array',
    UINT8CLAMPEDARRAY: 'uint8clampedarray',
    UNDEFINED: 'undefined',
    WEAKMAP: 'weakmap',
    WEAKSET: 'weakset',

    // Extra
    ALPHANUMERIC: 'alphanumeric',
    ANY: 'any',
    DATESTRING: 'datestring',
    EMAIL: 'email',
    FLOAT: 'float',
    INT: 'int',
    IP: 'ip',
    TIMESTRING: 'timestring',
    UUID: 'uuid',
    URL: 'url',
};